### ISSUE TITLE
 i3expo-ng doing nothing

### ISSUE THREAD

**Issue by kidpixo** [morrolinux/i3expo-ng#18]
Ciao Morro,
grande idea quel che ci voleva per i3! 
Passo all'inglese per rendere questa issue utile per altri utenti della grande rete.

<hr>

**[Steps]**

- I installed the requirements in a conda enviroment (sort of virtualens). 
- All the required packages are importable in python.
- Compiled `prtscn.c` without problems.
- Configuration is in the right place, and I adapted it to my monitors.
Simply, when I run `i3expod.py` nothing happens.

**[Info]**

I'm on Arch using pure i3wm, now DE.

**[Question]**

Any idea? Maybe pygame is the culprit?

**Comment by kidpixo** [comment]
nope, PyGame seems to be fine...

![2021-12-09_14-00-57-screenshot png](https://user-images.githubusercontent.com/2255209/145401221-247f4e9c-fe74-4dd4-ad34-a454abb75f45.png)

**Comment by morrolinux** [comment]
Hi,
You're not supposed to run `ptrscn`, see the REDME on [startup](https://github.com/morrolinux/i3expo-ng#startup).
