### ISSUE TITLE
Doesn't seem to work with named workspaces?

### ISSUE THREAD

**Issue by eater** [morrolinux/i3expo-ng#2]
I have workspaces with names like "1: main", "2: video", etc. The i3expo window displays them fine, but when I select the first workspace (for example) it creates a new empty workspace called "1" instead of going to "1: main".

**Comment by Giorgiofox** [comment]
I can confirm this. I was opening an issue for the same problem:)
I'm using workspace with name, using this:
`bindsym F4 exec i3-input -F 'rename workspace to "%s"' -P 'New name for this workspace: '`

Is very useful. 
As I can see, i3expo does not seem to work with workspace with a name containing space also, or sometime, it generate a workspace called "-1". 
I'm also having other problem with polybar, but I need to investigate about this. 
Thanks for this great project :)

**Comment by morrolinux** [comment]
That's right, I didn't use and support named workspaces. I just fixed it and it seems to be working alright now :)

> `bindsym F4 exec i3-input -F 'rename workspace to "%s"' -P 'New name for this workspace: '`

That's actually really handy... I might start using this after all

**Comment by morrolinux** [comment]
Feel free to reopen if necessary

**Comment by eater** [comment]
Working, thanks!
