### ISSUE TITLE
Workspace Transition Animations

### ISSUE THREAD

**Issue by Swivelgames** [morrolinux/i3expo-ng#21]
This is probably well outside the scope of this project, but in reading how this project works, I'm curious whether or not the same method could be employed in order to animation workspace transitions?

For instance, sliding to the left or right to the next workspace.

**Comment by morrolinux** [comment]
Well, that's *technically* outside the scope of this project. It's the compositor job to do such things, and i3 is only a WM, it doesn't do compositing. For that reason i3 setups are often coupled with an external compositor like "picom" that can provide stuff like drop shadows, window transparency and desktop switching animations. Unfortunately the only animation supported by "picom" as of now is the fading, but you could definitely ask them if they're interested in coding some other transitions or better yet try do it yourself :)
