### ISSUE TITLE
i3expod not launching

### ISSUE THREAD

**Issue by Mugworth** [morrolinux/i3expo-ng#25]
-- Linux Mint 23
-- python 3.10
-- i3 4.22

![2023-01-10_19-26](https://user-images.githubusercontent.com/62995382/211632409-e103451a-8c31-4359-b571-2765c8fc8112.png)

**Comment by morrolinux** [comment]
Monitor(s) configuration?

**Comment by Mugworth** [comment]
I have only one monitor, under DVI-D-0, 1920x1200 resolution

**Comment by morrolinux** [comment]
If you open a python interpreter and paste this:

```
import subprocess

def get_primary_output_name():
    stdout, stderr = subprocess.Popen('xrandr --listmonitors',
                                      shell=True, stdout=subprocess.PIPE).communicate()
    if stdout != '':
        monitorlines = stdout.decode().split("\n")
        # Search for the primary (marked with +*)
        # If none found (e.g. primary is on a disconnected output), take the first
        primary = None
        for m in monitorlines:
            if "+*" in m:
                primary = m
                break  # Early exit from the cycle
            elif "+" in m:
                primary = m  # We found a monitor. Keep it
        if primary != None:
            return primary.split()[-1]
    return None

get_primary_output_name()
```

what's the output?

**Comment by Mugworth** [comment]
Here it is
![2023-01-12_20-46](https://user-images.githubusercontent.com/62995382/212165966-6eee64f3-2330-4b20-9c97-4b606ba7086b.png)

**Comment by Mugworth** [comment]
I dont know how i didnt think about it earlier, but with default i3 configuration, i3expo is working perfectly, i will try to debugg my config and update this thread later, im sorry for wasting your time

**Comment by Mugworth** [comment]
Ok it seems its because of gaps, is expo not supposed to work with gaps or is it because of some bugs? My configuration of gaps:
![2023-01-12_21-26](https://user-images.githubusercontent.com/62995382/212173957-9a5c63de-be67-49f2-8a29-71378c9b1840.png)

**Comment by morrolinux** [comment]
Umh, interesting. So it's fine if you disable gaps... Well I do use gaps myself and it works, the only difference is I don't use negative values for gaps. Have you tried setting your outer gaps to something non-negative, like 0?

**Comment by Mugworth** [comment]
Yeah without negative value it's working as expected, i guess i can live without it, thank you :)
