### ISSUE TITLE
Problems in EndeavourOS

### ISSUE THREAD

**Issue by Andre0-0** [morrolinux/i3expo-ng#4]
Actually i'm using EndeavourOS with kde+i3.
As soon as i launch i3expod, it gives a black screen for about 5 seconds after creating the temporary workspace.
But then it doesn't show anything, it seems that it only creates the workspace.(I don't have named workspaces.)

**Comment by morrolinux** [comment]
How about you run the script from a shell and paste the output? :)

Il lun 25 gen 2021, 11:41 Andre0-0 <notifications@github.com> ha scritto:

**Comment by Andre0-0** [comment]
Command:
`./i3expod.py -f -w $HOME/Immagini/HorseHeadNebula.jpg`
Output:
`pygame 2.0.1 (SDL 2.0.14, Python 3.9.1)`
`Hello from the pygame community. https://www.pygame.org/contribute.html`

Then i send `SIGUSR1` to `i3expod.py`, but it execute the command without a text output on terminal.

**Comment by morrolinux** [comment]
Try again without `-f` option as I noticed that on some distros pygame won't just run in fullscreen mode

**Comment by Andre0-0** [comment]
> Try again without `-f` option as I noticed that on some distros pygame won't just run in fullscreen mode

It solved the problem.
Thank you.
(Ottimo lavoro comunque ;) )
