### ISSUE TITLE
i3expo non funziona

### ISSUE THREAD

**Issue by marmod75** [morrolinux/i3expo-ng#5]
Ciao morro,
seguo con molto interesse il tuo canale e ho provato a installare i3expo sulla mia manjaro con i3wm.
Ho seguito passo passo la tua guida, ma i3expo non va; se provo ad avviarlo da shell ottengo:

Traceback (most recent call last):
  File "/home/mario/i3expo-ng/./i3expod.py", line 790, in <module>
    read_config()
  File "/home/mario/i3expo-ng/./i3expod.py", line 166, in read_config
    for key in config['OUTPUT_ALIASES']:
  File "/usr/lib/python3.9/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'OUTPUT_ALIASES'

Scusa l'ignoranza ma non so davvero che pesci prendere!
Puoi aiutarmi? Grazie in anticipo per l'attenzione...

**Comment by morrolinux** [comment]
Ciao, copia il file di configurazione come da istruzioni del README

Il sab 30 gen 2021, 10:25 marmod75 <notifications@github.com> ha scritto:

**Comment by marmod75** [comment]
Ciao,
avevo già copiato il file defaultconfig dentro ~/.config/i3expo/config
La cartella non esisteva e l'ho creata... ma non funziona lo stesso.
Forse devo creare una cartella ~/.config/i3expo-ng/config dato che l'applicazione è dentro ~/i3expo-ng ?

**Comment by morrolinux** [comment]
Incolla il contenuto del file di configurazione che diamo un'occhiata.
Se questa copia l'hai fatta la settimana scorsa ti anticipo già che è
normale perché ho aggiunto alcuni parametri e dovresti rifarla

Il sab 30 gen 2021, 11:52 marmod75 <notifications@github.com> ha scritto:

**Comment by marmod75** [comment]
No, ho scaricato il codice stamattina...

[UI]

bgcolor = None

padding_percent_x = 4
padding_percent_y = 4
spacing_percent_x = 4
spacing_percent_y = 4

frame_width_px = None
frame_active_color = None
frame_inactive_color = None
frame_unknown_color = None
frame_nonexistant_color = None

tile_active_color = None
tile_inactive_color = None
tile_unknown_color = None
tile_nonexistant_color = None

names_show = None
names_font = None
names_fontsize = None
names_color = None

names_position = under
# names_position = inside

highlight_percentage = None

[OUTPUT_ALIASES]

DVI-D-0 = Center
HDMI-A-0 = Right
DisplayPort-0 = Left

**Comment by morrolinux** [comment]
1. Su che distro sei?
2. Se apri un terminale e scrivi `echo $XDG_CONFIG_HOME` e premi invio, cosa compare?

**Comment by marmod75** [comment]
1. manjaro 20.2.1 "nibia"
2. non compare nulla

**Comment by morrolinux** [comment]
Proviamo diversamente. Apri una shell e digita "python"

incolla questa riga e dai invio:
`from xdg.BaseDirectory import xdg_config_home`
incolla questa riga e dai invio:
`print(xdg_config_home)`

Cosa compare?

**Comment by marmod75** [comment]
compare:

/home/mario/.config

"mario" è il mio user...

**Comment by morrolinux** [comment]
Ok, apri una shell, incolla quanto segue e posta qui l'output:
`ls -l /home/mario/.config/i3expo/config ; cat !$`

**Comment by marmod75** [comment]
ls -l /home/mario/.config/i3expo/config ; cat ls
totale 4
-rw-r--r-- 1 mario mario 585 27 gen 21.08 defaultconfig
cat: ls: File o directory non esistente

**Comment by morrolinux** [comment]
> ls -l /home/mario/.config/i3expo/config ; cat ls

Questo non è il comando che ti ho dato, probabilmente l'hai battuto a mano e commesso un errore di battitura. Se vuoi che ti aiuti, copia a incolla a terminale come richiesto

**Comment by morrolinux** [comment]
Anzi, ancora meglio, usa questo:
`ls -l /home/mario/.config/i3expo/config && cat !$`

**Comment by marmod75** [comment]
Mi spiace, ma il comando l'ho immesso con il copia &incolla.
L'output è questo...

[mario@ux330 ~]$ ls -l /home/mario/.config/i3expo/config && cat !$
ls -l /home/mario/.config/i3expo/config && cat ls
totale 4
-rw-r--r-- 1 mario mario 585 27 gen 21.08 defaultconfig
cat: ls: File o directory non esistente

**Comment by morrolinux** [comment]
Vedo.. la ragione per cui fallisce è che nella tua home `.config/i3expo/config` è una cartella e non il file `defaultconfig` rinominato a `config`. Devi eliminare quella cartella e rifare da capo, Ho aggiornato le istruzioni con i comandi espliciti così che non ci si possa confondere.
Per eliminare la cartella: `rm -rf .config/i3expo`

**Comment by marmod75** [comment]
...adesso sembra andare.
Però, non mi funziona bene e mi spiego: quando premo mod+tab alcune volte funziona, altre (la maggioranza) viene visualizzato uno schermo nero per un paio di secondi, poi apre un desktop virtuale vuoto che sulla d-bar in basso prende il nome di "i3expod-temporary-workspace" (invece di 1, 2, ecc...).

Intanto, ti ringrazio per la pazienza e le dritte...

**Comment by morrolinux** [comment]
Che scheda video hai? La integrata Intel?

Prova a togliere il flag -f per il fullscreen.
Pygame in alcuni casi va in crash su una schermata nera se impostato in fullscreen.

**Comment by marmod75** [comment]
Si, è integrata Intel.
Ho fatto come dici e, adesso, sembra funzionare tutto... ogni tanto mi apre l'app accanto le altre finestre, ma in linea di massima funziona...
Hai fatto una cosa veramente utile: i3 è comodo e, per i miei gusti, perfetto per lavorare... venivo da pop_os che è comodo ma lento e instabile... tu hai messo la ciliegina sulla torta.
Grazie mille, il tuo aiuto è stato prezioso!

**Comment by morrolinux** [comment]
Interessante.. sembra sia un problema che si presenta consistentemente con le GPU Intel a prescindere dalla distro. Bene allora, buon divertimento :)
