### ISSUE TITLE
Black screen dopo aver mandato il segnale -SIGUSR1

### ISSUE THREAD

**Issue by Jei-sKappa** [morrolinux/i3expo-ng#6]
Buonasera, dopo aver installato tutte le dipendenze di python ecc.. mettendo le scorciatoie di avvio nel config di i3 dando il segnale sigusr1 si avvia ma lo schermo rimane nero e dopo 4 secondi sparisce.

File conf di i3:
exec_always --no-startup-id "~/git/i3expo-ng/i3expod.py -f -w /home/jac/.wallpaper/dark-archlinux2.png"
bindsym Mod1+Tab exec --no-startup-id "killall -s SIGUSR1 i3expod.py"

PS
Come si poteva notare dalla conf di i3 ho clonato i3expo in /home/git e non in /home, non credo sia un problema questo..

Buona serata!

**Comment by morrolinux** [comment]
Ciao, leggi il README, è quasi sicuramente l'opzione di fullscreen (-f) che
ti da problemi :)

Il mer 17 feb 2021, 18:49 Jei-sKappa <notifications@github.com> ha scritto:

**Comment by Jei-sKappa** [comment]
Grazie mille non ci avevo fatto caso!!
