### ISSUE TITLE
Moduli python da installare e import ridondante

### ISSUE THREAD

**Issue by aleemont** [morrolinux/i3expo-ng#9]
Some Python modules (Pillow [formerly PIL] and xdg) require manual installation from PIP, you should include those into `README.md`

Some `import`s are redundant: 

`22 from PIL import Image, ImageDraw`
`23 from xdg.BaseDirectory import xdg_config_home`
`24 from contextlib import suppress`
`25 from PIL import Image, ImageFilter, ImageEnhance`

Can be simplified with:

`22 from xdg.BaseDirectory import xdg_config_home`
`23 from contextlib import suppress`
`24 from PIL import Image, ImageFilter, ImageEnhance, ImageDraw`

Seems to work nicely. Great job.

**Comment by morrolinux** [comment]
Thanks! 
I suggest you to create a pull request containing those changes on two separate commits to get contribution officially recognized :)
Are you willing to do that or shall I just write the commit myself? let me know!

PS: Also remember to use english on this repo as it's of worldwide potential interest.

**Comment by aleemont** [comment]
Will make a pull request tomorrow.

**Comment by aleemont** [comment]
Created pull-request. Closing
